services:
  db:
    image: mysql
    container_name: mysqltest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - exerciciojava_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  exerciciojava_data:
